/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package server;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2019-05-08")
public class ZborDTO implements org.apache.thrift.TBase<ZborDTO, ZborDTO._Fields>, java.io.Serializable, Cloneable, Comparable<ZborDTO> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ZborDTO");

  private static final org.apache.thrift.protocol.TField ORA_FIELD_DESC = new org.apache.thrift.protocol.TField("ora", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField LOCURI_FIELD_DESC = new org.apache.thrift.protocol.TField("locuri", org.apache.thrift.protocol.TType.I32, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ZborDTOStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ZborDTOTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String ora; // required
  public int locuri; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ORA((short)1, "ora"),
    LOCURI((short)2, "locuri");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ORA
          return ORA;
        case 2: // LOCURI
          return LOCURI;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __LOCURI_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ORA, new org.apache.thrift.meta_data.FieldMetaData("ora", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.LOCURI, new org.apache.thrift.meta_data.FieldMetaData("locuri", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ZborDTO.class, metaDataMap);
  }

  public ZborDTO() {
  }

  public ZborDTO(
    java.lang.String ora,
    int locuri)
  {
    this();
    this.ora = ora;
    this.locuri = locuri;
    setLocuriIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ZborDTO(ZborDTO other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetOra()) {
      this.ora = other.ora;
    }
    this.locuri = other.locuri;
  }

  public ZborDTO deepCopy() {
    return new ZborDTO(this);
  }

  @Override
  public void clear() {
    this.ora = null;
    setLocuriIsSet(false);
    this.locuri = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getOra() {
    return this.ora;
  }

  public ZborDTO setOra(@org.apache.thrift.annotation.Nullable java.lang.String ora) {
    this.ora = ora;
    return this;
  }

  public void unsetOra() {
    this.ora = null;
  }

  /** Returns true if field ora is set (has been assigned a value) and false otherwise */
  public boolean isSetOra() {
    return this.ora != null;
  }

  public void setOraIsSet(boolean value) {
    if (!value) {
      this.ora = null;
    }
  }

  public int getLocuri() {
    return this.locuri;
  }

  public ZborDTO setLocuri(int locuri) {
    this.locuri = locuri;
    setLocuriIsSet(true);
    return this;
  }

  public void unsetLocuri() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __LOCURI_ISSET_ID);
  }

  /** Returns true if field locuri is set (has been assigned a value) and false otherwise */
  public boolean isSetLocuri() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __LOCURI_ISSET_ID);
  }

  public void setLocuriIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __LOCURI_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ORA:
      if (value == null) {
        unsetOra();
      } else {
        setOra((java.lang.String)value);
      }
      break;

    case LOCURI:
      if (value == null) {
        unsetLocuri();
      } else {
        setLocuri((java.lang.Integer)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ORA:
      return getOra();

    case LOCURI:
      return getLocuri();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ORA:
      return isSetOra();
    case LOCURI:
      return isSetLocuri();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof ZborDTO)
      return this.equals((ZborDTO)that);
    return false;
  }

  public boolean equals(ZborDTO that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_ora = true && this.isSetOra();
    boolean that_present_ora = true && that.isSetOra();
    if (this_present_ora || that_present_ora) {
      if (!(this_present_ora && that_present_ora))
        return false;
      if (!this.ora.equals(that.ora))
        return false;
    }

    boolean this_present_locuri = true;
    boolean that_present_locuri = true;
    if (this_present_locuri || that_present_locuri) {
      if (!(this_present_locuri && that_present_locuri))
        return false;
      if (this.locuri != that.locuri)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetOra()) ? 131071 : 524287);
    if (isSetOra())
      hashCode = hashCode * 8191 + ora.hashCode();

    hashCode = hashCode * 8191 + locuri;

    return hashCode;
  }

  @Override
  public int compareTo(ZborDTO other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetOra()).compareTo(other.isSetOra());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOra()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ora, other.ora);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.valueOf(isSetLocuri()).compareTo(other.isSetLocuri());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLocuri()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.locuri, other.locuri);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ZborDTO(");
    boolean first = true;

    sb.append("ora:");
    if (this.ora == null) {
      sb.append("null");
    } else {
      sb.append(this.ora);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("locuri:");
    sb.append(this.locuri);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ZborDTOStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ZborDTOStandardScheme getScheme() {
      return new ZborDTOStandardScheme();
    }
  }

  private static class ZborDTOStandardScheme extends org.apache.thrift.scheme.StandardScheme<ZborDTO> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ZborDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ORA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.ora = iprot.readString();
              struct.setOraIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // LOCURI
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.locuri = iprot.readI32();
              struct.setLocuriIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ZborDTO struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ora != null) {
        oprot.writeFieldBegin(ORA_FIELD_DESC);
        oprot.writeString(struct.ora);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(LOCURI_FIELD_DESC);
      oprot.writeI32(struct.locuri);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ZborDTOTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ZborDTOTupleScheme getScheme() {
      return new ZborDTOTupleScheme();
    }
  }

  private static class ZborDTOTupleScheme extends org.apache.thrift.scheme.TupleScheme<ZborDTO> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ZborDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetOra()) {
        optionals.set(0);
      }
      if (struct.isSetLocuri()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetOra()) {
        oprot.writeString(struct.ora);
      }
      if (struct.isSetLocuri()) {
        oprot.writeI32(struct.locuri);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ZborDTO struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.ora = iprot.readString();
        struct.setOraIsSet(true);
      }
      if (incoming.get(1)) {
        struct.locuri = iprot.readI32();
        struct.setLocuriIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

