/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace CSharp
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Bilet : TBase
  {
    private int _ID;
    private int _ZborId;
    private int _ClientId;
    private string _turisti;
    private int _locuri;

    public int ID
    {
      get
      {
        return _ID;
      }
      set
      {
        __isset.ID = true;
        this._ID = value;
      }
    }

    public int ZborId
    {
      get
      {
        return _ZborId;
      }
      set
      {
        __isset.ZborId = true;
        this._ZborId = value;
      }
    }

    public int ClientId
    {
      get
      {
        return _ClientId;
      }
      set
      {
        __isset.ClientId = true;
        this._ClientId = value;
      }
    }

    public string Turisti
    {
      get
      {
        return _turisti;
      }
      set
      {
        __isset.turisti = true;
        this._turisti = value;
      }
    }

    public int Locuri
    {
      get
      {
        return _locuri;
      }
      set
      {
        __isset.locuri = true;
        this._locuri = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ID;
      public bool ZborId;
      public bool ClientId;
      public bool turisti;
      public bool locuri;
    }

    public Bilet() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                ID = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                ZborId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                ClientId = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                Turisti = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.I32) {
                Locuri = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Bilet");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.ID) {
          field.Name = "ID";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ID);
          oprot.WriteFieldEnd();
        }
        if (__isset.ZborId) {
          field.Name = "ZborId";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ZborId);
          oprot.WriteFieldEnd();
        }
        if (__isset.ClientId) {
          field.Name = "ClientId";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ClientId);
          oprot.WriteFieldEnd();
        }
        if (Turisti != null && __isset.turisti) {
          field.Name = "turisti";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Turisti);
          oprot.WriteFieldEnd();
        }
        if (__isset.locuri) {
          field.Name = "locuri";
          field.Type = TType.I32;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Locuri);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Bilet(");
      bool __first = true;
      if (__isset.ID) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ID: ");
        __sb.Append(ID);
      }
      if (__isset.ZborId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ZborId: ");
        __sb.Append(ZborId);
      }
      if (__isset.ClientId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ClientId: ");
        __sb.Append(ClientId);
      }
      if (Turisti != null && __isset.turisti) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Turisti: ");
        __sb.Append(Turisti);
      }
      if (__isset.locuri) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Locuri: ");
        __sb.Append(Locuri);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
