/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace CSharp
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class Zbor : TBase
  {
    private int _ID;
    private string _destinatie;
    private string _plecare;
    private string _aeroport;
    private int _locuri;

    public int ID
    {
      get
      {
        return _ID;
      }
      set
      {
        __isset.ID = true;
        this._ID = value;
      }
    }

    public string Destinatie
    {
      get
      {
        return _destinatie;
      }
      set
      {
        __isset.destinatie = true;
        this._destinatie = value;
      }
    }

    public string Plecare
    {
      get
      {
        return _plecare;
      }
      set
      {
        __isset.plecare = true;
        this._plecare = value;
      }
    }

    public string Aeroport
    {
      get
      {
        return _aeroport;
      }
      set
      {
        __isset.aeroport = true;
        this._aeroport = value;
      }
    }

    public int Locuri
    {
      get
      {
        return _locuri;
      }
      set
      {
        __isset.locuri = true;
        this._locuri = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ID;
      public bool destinatie;
      public bool plecare;
      public bool aeroport;
      public bool locuri;
    }

    public Zbor() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                ID = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Destinatie = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                Plecare = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.String) {
                Aeroport = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.I32) {
                Locuri = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("Zbor");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.ID) {
          field.Name = "ID";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(ID);
          oprot.WriteFieldEnd();
        }
        if (Destinatie != null && __isset.destinatie) {
          field.Name = "destinatie";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Destinatie);
          oprot.WriteFieldEnd();
        }
        if (Plecare != null && __isset.plecare) {
          field.Name = "plecare";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Plecare);
          oprot.WriteFieldEnd();
        }
        if (Aeroport != null && __isset.aeroport) {
          field.Name = "aeroport";
          field.Type = TType.String;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Aeroport);
          oprot.WriteFieldEnd();
        }
        if (__isset.locuri) {
          field.Name = "locuri";
          field.Type = TType.I32;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Locuri);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("Zbor(");
      bool __first = true;
      if (__isset.ID) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ID: ");
        __sb.Append(ID);
      }
      if (Destinatie != null && __isset.destinatie) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Destinatie: ");
        __sb.Append(Destinatie);
      }
      if (Plecare != null && __isset.plecare) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Plecare: ");
        __sb.Append(Plecare);
      }
      if (Aeroport != null && __isset.aeroport) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Aeroport: ");
        __sb.Append(Aeroport);
      }
      if (__isset.locuri) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Locuri: ");
        __sb.Append(Locuri);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
