/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace CSharp
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ZborDTO : TBase
  {
    private string _ora;
    private int _locuri;

    public string Ora
    {
      get
      {
        return _ora;
      }
      set
      {
        __isset.ora = true;
        this._ora = value;
      }
    }

    public int Locuri
    {
      get
      {
        return _locuri;
      }
      set
      {
        __isset.locuri = true;
        this._locuri = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ora;
      public bool locuri;
    }

    public ZborDTO() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                Ora = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                Locuri = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ZborDTO");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Ora != null && __isset.ora) {
          field.Name = "ora";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Ora);
          oprot.WriteFieldEnd();
        }
        if (__isset.locuri) {
          field.Name = "locuri";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Locuri);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ZborDTO(");
      bool __first = true;
      if (Ora != null && __isset.ora) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Ora: ");
        __sb.Append(Ora);
      }
      if (__isset.locuri) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Locuri: ");
        __sb.Append(Locuri);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
